version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # 初期構築時はボリュームをコメントアウトしておく
    volumes:
      - ./app:/var/www/app
    depends_on:
      - db
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: todo_list
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" # 3306は使用中であることを考慮して3307を指定
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
